root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -buildvcs=false -o main ."
  bin = "main"
  full_bin = "./main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  follow_symlink = true
  log = "build.log"
  poll = false
  delay = 1000
[log]
  time = true
[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
